from typing import Protocol


class MicrocontrollerInterface(Protocol):
    def _init_serial(self): ...

    def arm(self, block=True): ...

    def disarm(self, block=True): ...

    def request_pixhawk_to_telemetry(self, telemetry_state): ...

    def set_mode(self, mode): ...

    def rc_channels_override_send(self, ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8): ...

    def get_mode(self): ...
